LogFile /tmp/clamd.log
LogTime yes
Foreground yes
TCPSocket 3310
LocalSocket /tmp/clamd.sock
MaxThreads 4
StreamMaxLength 30M
MaxFileSize 30M
MaxScanSize 120M
MaxRecursion 10
MaxFiles 500
ReadTimeout 60
CommandReadTimeout 30
AlertEncrypted yes
AlertEncryptedArchive yes
AlertEncryptedDoc yes
DetectPUA yes
ScanPDF yes
ScanOLE2 yes
ScanArchive yes
