"""Idempotent virtual-key bootstrap (04-04 §4.4). Allowed aliases / rpm come from ``callbacks.core.VIRTUAL_KEYS`` (single source).

    python init_keys.py [--rotate <alias>] [--gateway http://localhost:4000]

Keys are written to ``infra/llm-gateway/.keys.env`` (gitignored) as ``<ALIAS>_KEY=...``; compose loads it via env_file.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import httpx

HERE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(HERE))
from callbacks.core import VIRTUAL_KEYS  # noqa: E402

KEYS_FILE = HERE / ".keys.env"


def env_name(alias: str) -> str:
    return alias.upper().replace("-", "_") + "_KEY"


def load_existing() -> dict[str, str]:
    out: dict[str, str] = {}
    if KEYS_FILE.exists():
        for line in KEYS_FILE.read_text(encoding="utf-8").splitlines():
            if "=" in line and not line.startswith("#"):
                k, v = line.split("=", 1)
                out[k] = v
    return out


def payload(alias: str, spec: dict) -> dict:
    return {"key_alias": alias, "models": spec["models"] or [], "rpm_limit": spec["rpm"], "max_parallel_requests": 5, "metadata": {"service": alias}, "budget_duration": "1d"}


def ensure_key(client: httpx.Client, alias: str, spec: dict, existing: dict[str, str], rotate: bool) -> str:
    name = env_name(alias)
    if name in existing and not rotate:
        r = client.post("/key/update", json={"key": existing[name], **payload(alias, spec)})
        if r.status_code < 300:
            return existing[name]
    new = client.post("/key/generate", json=payload(alias, spec))
    new.raise_for_status()
    key = new.json()["key"]
    if rotate and name in existing:  # old key is deleted only after the new one exists
        client.post("/key/delete", json={"keys": [existing[name]]})
    return key


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--gateway", default=os.environ.get("GW", "http://localhost:4000"))
    ap.add_argument("--rotate", help="alias to rotate")
    a = ap.parse_args()
    master = os.environ.get("LITELLM_MASTER_KEY")
    if not master:
        print("LITELLM_MASTER_KEY not set", file=sys.stderr)
        return 2
    existing = load_existing()
    with httpx.Client(base_url=a.gateway, headers={"Authorization": f"Bearer {master}"}, timeout=30) as c:
        for alias, spec in VIRTUAL_KEYS.items():
            if a.rotate and alias != a.rotate:
                continue
            existing[env_name(alias)] = ensure_key(c, alias, spec, existing, rotate=bool(a.rotate))
            print(f"ok {alias}")
    KEYS_FILE.write_text("# generated by init_keys.py - gitignored\n" + "".join(f"{k}={v}\n" for k, v in sorted(existing.items())), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
