"""Write a Mermaid ER diagram of the hospital DB from SQLAlchemy metadata -> docs/er-hospital.md."""

import pathlib
import sys

sys.path.insert(0, "hospital/api")
import app.models  # noqa: E402,F401
from app.db.base import Base  # noqa: E402

lines = ["# Hospital DB ER diagram (generated by scripts/gen_er.py)", "", "```mermaid", "erDiagram"]
for t in sorted(Base.metadata.tables.values(), key=lambda t: t.name):
    for fk in t.foreign_keys:
        lines.append(f'  {fk.column.table.name} ||--o{{ {t.name} : "{fk.parent.name}"')
for t in sorted(Base.metadata.tables.values(), key=lambda t: t.name):
    lines.append(f"  {t.name} {{")
    for c in t.columns:
        kind = "PK" if c.primary_key else ("FK" if c.foreign_keys else "")
        lines.append(f"    {str(c.type).split('(')[0].replace(' ', '_')} {c.name} {kind}".rstrip())
    lines.append("  }")
lines += ["```", ""]
pathlib.Path("docs/er-hospital.md").write_text("\n".join(lines))
print("wrote docs/er-hospital.md")
